version: "3.7"
services:

  fastapi:
    container_name: app
    build: .
    ports:
      - "80:80"
    depends_on:
      - database

  database:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
    ports:
      - "5432:5432"
volumes:
  postgres: